# Generated by Django 5.0.6 on 2024-06-06 21:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('cod_persona', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999999)])),
                ('pnombre', models.CharField(max_length=20)),
                ('snombre', models.CharField(max_length=20, null=True)),
                ('apellidop', models.CharField(max_length=20)),
                ('apellidom', models.CharField(max_length=20)),
                ('correo', models.EmailField(error_messages='El correo maldito Peruano', max_length=254)),
                ('direccion', models.CharField(max_length=50)),
                ('celular', models.IntegerField(validators=[django.core.validators.MinValueValidator(100000000), django.core.validators.MaxValueValidator(999999999)], verbose_name='Fono')),
                ('region', models.CharField(choices=[('ÑUBLE', 'Region del Ñuble'), ('ARAUCANIA', 'Region de la Araucania'), ('BIOBIO', 'Region del Bio-Bio')], default='CONCEPCION', max_length=25)),
                ('info_adicional', models.CharField(max_length=100)),
                ('imagen', models.ImageField(null=True, upload_to='personas')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('cod_producto', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999999)])),
                ('nombre', models.CharField(max_length=50)),
                ('tipo_producto', models.CharField(choices=[('CUCHILLA', 'Cuchilla'), ('ARMA', 'Arma'), ('ROPA', 'Ropa')], default='OTRO PRODUCTO', max_length=10)),
                ('tipo_municion', models.CharField(choices=[('AIRSOFT', 'Airsoft'), ('POSTON', 'Poston'), ('BALIN', 'Balin'), ('OTRO', 'Otro')], default='OTRO', max_length=100)),
                ('precio', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(999999999)], verbose_name='Dinero')),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('imagen', models.ImageField(null=True, upload_to='productos')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombusuario', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pwd', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('idcompra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_compra', models.DateField(verbose_name='Fecha de compra')),
                ('estado', models.CharField(choices=[('CANCELADO', 'Cancelado'), ('PENDIENTE', 'Pendiente'), ('ENTREGADO', 'Entregado')], default='ENTREGADO', max_length=100)),
                ('imagenenvio', models.ImageField(null=True, upload_to='imagenenvios')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplicacion.usuario')),
            ],
        ),
    ]
