# Generated by Django 5.0.6 on 2024-06-16 22:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_alter_envio_estado_alter_persona_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('correo', models.EmailField(max_length=254)),
                ('usuario', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=100)),
                ('fecha_pedido', models.DateField()),
                ('boleta', models.CharField(choices=[('con_factura', 'Con factura'), ('con_boleta', 'Con boleta')], max_length=15)),
                ('estado', models.CharField(choices=[('cancelado', 'Cancelado'), ('pendiente', 'Pendiente'), ('finalizado', 'Finalizado')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('usuario', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=20)),
                ('contraseña', models.CharField(max_length=18)),
            ],
        ),
        migrations.AlterField(
            model_name='persona',
            name='correo',
            field=models.EmailField(error_messages='El correo', max_length=254),
        ),
        migrations.AlterField(
            model_name='persona',
            name='region',
            field=models.CharField(choices=[('ÑUBLE', 'Region del Ñuble'), ('ARAUCANIA', 'Region de la Araucania'), ('BIOBIO', 'Region del Bio-Bio')], default='CONCEPCION', max_length=25),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cod_producto',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(999999999)]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_municion',
            field=models.CharField(choices=[('POSTON', 'Poston'), ('OTRO', 'Otro'), ('BALIN', 'Balin'), ('AIRSOFT', 'Airsoft')], default='OTRO', max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_producto',
            field=models.CharField(choices=[('ARMA', 'Arma'), ('CUCHILLA', 'Cuchilla'), ('ROPA', 'Ropa')], default='OTRO PRODUCTO', max_length=10),
        ),
    ]
