# Generated by Django 5.0.6 on 2024-06-25 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0008_alter_envio_estado_alter_envio_fecha_compra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.envio'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='region',
            field=models.CharField(choices=[('ÑUBLE', 'Region del Ñuble'), ('BIOBIO', 'Region del Bio-Bio'), ('ARAUCANIA', 'Region de la Araucania')], default='CONCEPCION', max_length=25),
        ),
        migrations.AlterField(
            model_name='persona',
            name='region',
            field=models.CharField(choices=[('ÑUBLE', 'Region del Ñuble'), ('BIOBIO', 'Region del Bio-Bio'), ('ARAUCANIA', 'Region de la Araucania')], default='CONCEPCION', max_length=25),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_municion',
            field=models.CharField(choices=[('BALIN', 'Balin'), ('AIRSOFT', 'Airsoft'), ('POSTON', 'Poston'), ('OTRO', 'Otro')], default='OTRO', max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_producto',
            field=models.CharField(choices=[('ARMA', 'Arma'), ('ROPA', 'Ropa'), ('CUCHILLA', 'Cuchilla')], default='OTRO PRODUCTO', max_length=10),
        ),
    ]
