# Generated by Django 5.0.6 on 2024-06-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0013_alter_envio_estado_alter_pedido_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='estado',
            field=models.CharField(choices=[('CANCELADO', 'Cancelado'), ('PENDIENTE', 'Pendiente'), ('ENTREGADO', 'Entregado')], default='PENDIENTE', max_length=100),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='region',
            field=models.CharField(choices=[('ARAUCANIA', 'Region de la Araucania'), ('ÑUBLE', 'Region del Ñuble'), ('BIOBIO', 'Region del Bio-Bio')], default='CONCEPCION', max_length=25),
        ),
        migrations.AlterField(
            model_name='persona',
            name='region',
            field=models.CharField(choices=[('ARAUCANIA', 'Region de la Araucania'), ('ÑUBLE', 'Region del Ñuble'), ('BIOBIO', 'Region del Bio-Bio')], default='CONCEPCION', max_length=25),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_municion',
            field=models.CharField(choices=[('BALIN', 'Balin'), ('OTRO', 'Otro'), ('AIRSOFT', 'Airsoft'), ('POSTON', 'Poston')], default='OTRO', max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_producto',
            field=models.CharField(choices=[('CUCHILLA', 'Cuchilla'), ('ROPA', 'Ropa'), ('ARMA', 'Arma')], default='OTRO PRODUCTO', max_length=10),
        ),
    ]
