# Generated by Django 5.0.6 on 2024-06-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0015_pedido_usuario_alter_pedido_region_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='envio',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=100),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='region',
            field=models.CharField(choices=[('ÑUBLE', 'Region del Ñuble'), ('ARAUCANIA', 'Region de la Araucania'), ('BIOBIO', 'Region del Bio-Bio')], default='CONCEPCION', max_length=25),
        ),
        migrations.AlterField(
            model_name='persona',
            name='region',
            field=models.CharField(choices=[('ÑUBLE', 'Region del Ñuble'), ('ARAUCANIA', 'Region de la Araucania'), ('BIOBIO', 'Region del Bio-Bio')], default='CONCEPCION', max_length=25),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_municion',
            field=models.CharField(choices=[('BALIN', 'Balin'), ('OTRO', 'Otro'), ('POSTON', 'Poston'), ('AIRSOFT', 'Airsoft')], default='OTRO', max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_producto',
            field=models.CharField(choices=[('CUCHILLA', 'Cuchilla'), ('ROPA', 'Ropa'), ('ARMA', 'Arma')], default='OTRO PRODUCTO', max_length=10),
        ),
    ]
