# Generated by Django 5.0.6 on 2024-06-28 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0016_remove_pedido_usuario_alter_envio_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='aplicacion.usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='region',
            field=models.CharField(choices=[('BIOBIO', 'Region del Bio-Bio'), ('ARAUCANIA', 'Region de la Araucania'), ('ÑUBLE', 'Region del Ñuble')], default='CONCEPCION', max_length=25),
        ),
        migrations.AlterField(
            model_name='persona',
            name='region',
            field=models.CharField(choices=[('BIOBIO', 'Region del Bio-Bio'), ('ARAUCANIA', 'Region de la Araucania'), ('ÑUBLE', 'Region del Ñuble')], default='CONCEPCION', max_length=25),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_municion',
            field=models.CharField(choices=[('AIRSOFT', 'Airsoft'), ('OTRO', 'Otro'), ('POSTON', 'Poston'), ('BALIN', 'Balin')], default='OTRO', max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_producto',
            field=models.CharField(choices=[('ROPA', 'Ropa'), ('CUCHILLA', 'Cuchilla'), ('ARMA', 'Arma')], default='OTRO PRODUCTO', max_length=10),
        ),
    ]
