# Generated by Django 5.0.6 on 2024-06-28 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0018_remove_pedido_usuario_alter_envio_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.PROTECT, to='aplicacion.usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='envio',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CANCELADO', 'Cancelado'), ('ENTREGADO', 'Entregado')], default='PENDIENTE', max_length=100),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='region',
            field=models.CharField(choices=[('ÑUBLE', 'Region del Ñuble'), ('BIOBIO', 'Region del Bio-Bio'), ('ARAUCANIA', 'Region de la Araucania')], default='CONCEPCION', max_length=25),
        ),
        migrations.AlterField(
            model_name='persona',
            name='region',
            field=models.CharField(choices=[('ÑUBLE', 'Region del Ñuble'), ('BIOBIO', 'Region del Bio-Bio'), ('ARAUCANIA', 'Region de la Araucania')], default='CONCEPCION', max_length=25),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_municion',
            field=models.CharField(choices=[('BALIN', 'Balin'), ('OTRO', 'Otro'), ('AIRSOFT', 'Airsoft'), ('POSTON', 'Poston')], default='OTRO', max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_producto',
            field=models.CharField(choices=[('ARMA', 'Arma'), ('ROPA', 'Ropa'), ('CUCHILLA', 'Cuchilla')], default='OTRO PRODUCTO', max_length=10),
        ),
    ]
