# Generated by Django 5.0.6 on 2024-07-07 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0019_pedido_usuario_alter_envio_estado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='user',
            field=models.OneToOneField(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='persona', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='envio',
            name='estado',
            field=models.CharField(choices=[('CANCELADO', 'Cancelado'), ('PENDIENTE', 'Pendiente'), ('ENTREGADO', 'Entregado')], default='PENDIENTE', max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_municion',
            field=models.CharField(choices=[('BALIN', 'Balin'), ('POSTON', 'Poston'), ('OTRO', 'Otro'), ('AIRSOFT', 'Airsoft')], default='OTRO', max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_producto',
            field=models.CharField(choices=[('ROPA', 'Ropa'), ('ARMA', 'Arma'), ('CUCHILLA', 'Cuchilla')], default='OTRO PRODUCTO', max_length=10),
        ),
    ]
