# Generated by Django 5.0.6 on 2024-07-08 23:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0019_pedido_usuario_alter_envio_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='estado',
            field=models.CharField(choices=[('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado'), ('PENDIENTE', 'Pendiente')], default='PENDIENTE', max_length=100),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='region',
            field=models.CharField(choices=[('ARAUCANIA', 'Region de la Araucania'), ('BIOBIO', 'Region del Bio-Bio'), ('ÑUBLE', 'Region del Ñuble')], default='CONCEPCION', max_length=25),
        ),
        migrations.AlterField(
            model_name='persona',
            name='region',
            field=models.CharField(choices=[('ARAUCANIA', 'Region de la Araucania'), ('BIOBIO', 'Region del Bio-Bio'), ('ÑUBLE', 'Region del Ñuble')], default='CONCEPCION', max_length=25),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_municion',
            field=models.CharField(choices=[('BALIN', 'Balin'), ('AIRSOFT', 'Airsoft'), ('POSTON', 'Poston'), ('OTRO', 'Otro')], default='OTRO', max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_producto',
            field=models.CharField(choices=[('ARMA', 'Arma'), ('CUCHILLA', 'Cuchilla'), ('ROPA', 'Ropa')], default='OTRO PRODUCTO', max_length=10),
        ),
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='aplicacion.carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.producto')),
            ],
        ),
    ]
