# Generated by Django 5.0.6 on 2024-07-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0021_remove_usuario_user_alter_envio_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='estado',
            field=models.CharField(choices=[('CANCELADO', 'Cancelado'), ('ENTREGADO', 'Entregado'), ('PENDIENTE', 'Pendiente')], default='PENDIENTE', max_length=100),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='region',
            field=models.CharField(choices=[('ARAUCANIA', 'Region de la Araucania'), ('BIOBIO', 'Region del Bio-Bio'), ('ÑUBLE', 'Region del Ñuble')], default='CONCEPCION', max_length=25),
        ),
        migrations.AlterField(
            model_name='persona',
            name='region',
            field=models.CharField(choices=[('ARAUCANIA', 'Region de la Araucania'), ('BIOBIO', 'Region del Bio-Bio'), ('ÑUBLE', 'Region del Ñuble')], default='CONCEPCION', max_length=25),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_municion',
            field=models.CharField(choices=[('BALIN', 'Balin'), ('AIRSOFT', 'Airsoft'), ('OTRO', 'Otro'), ('POSTON', 'Poston')], default='OTRO', max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_producto',
            field=models.CharField(choices=[('ARMA', 'Arma'), ('CUCHILLA', 'Cuchilla'), ('ROPA', 'Ropa')], default='OTRO PRODUCTO', max_length=10),
        ),
    ]
