# Generated by Django 5.0.6 on 2024-07-07 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0022_alter_envio_estado_alter_pedido_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CANCELADO', 'Cancelado'), ('ENTREGADO', 'Entregado')], default='PENDIENTE', max_length=100),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='region',
            field=models.CharField(choices=[('BIOBIO', 'Region del Bio-Bio'), ('ARAUCANIA', 'Region de la Araucania'), ('ÑUBLE', 'Region del Ñuble')], default='CONCEPCION', max_length=25),
        ),
        migrations.AlterField(
            model_name='persona',
            name='region',
            field=models.CharField(choices=[('BIOBIO', 'Region del Bio-Bio'), ('ARAUCANIA', 'Region de la Araucania'), ('ÑUBLE', 'Region del Ñuble')], default='CONCEPCION', max_length=25),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_municion',
            field=models.CharField(choices=[('OTRO', 'Otro'), ('POSTON', 'Poston'), ('BALIN', 'Balin'), ('AIRSOFT', 'Airsoft')], default='OTRO', max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_producto',
            field=models.CharField(choices=[('ARMA', 'Arma'), ('ROPA', 'Ropa'), ('CUCHILLA', 'Cuchilla')], default='OTRO PRODUCTO', max_length=10),
        ),
    ]
